# Generated by Django 5.2.14 on 2026-06-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.URLField(blank=True, default='', max_length=1000)),
                ('published_date', models.CharField(blank=True, default='', max_length=50)),
                ('categories', models.CharField(blank=True, default='', max_length=500)),
                ('google_books_id', models.CharField(blank=True, default='', max_length=100)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_contact', models.CharField(blank=True, default='', help_text='Email, phone, or social handle', max_length=300)),
                ('location', models.CharField(blank=True, default='', help_text='Barangay/City for meetup', max_length=300)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('worn', 'Worn')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Any extra info about the book')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='favoritebook',
            options={},
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_contact', models.CharField(help_text='Email, phone, or social handle', max_length=300)),
                ('message', models.TextField(blank=True, default='', help_text='Optional message to the owner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='books.communitybook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
