# Generated by Django 5.2.14 on 2026-06-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_communitybook_alter_favoritebook_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitybook',
            name='thumbnail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
