# Generated by Django 5.2.14 on 2026-06-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_communitybook_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='requester_contact',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='communitybook',
            name='location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='communitybook',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='communitybook',
            name='owner_contact',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
