# Generated by Django 5.2.14 on 2026-06-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_borrowrequest_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='request_type',
            field=models.CharField(choices=[('borrow', 'Borrow'), ('swap', 'Swap')], default='borrow', max_length=10),
        ),
        migrations.AddField(
            model_name='communitybook',
            name='listing_type',
            field=models.CharField(choices=[('borrow', 'Borrow'), ('swap', 'Swap'), ('both', 'Borrow or Swap')], default='borrow', max_length=10),
        ),
    ]
