# Generated by Django 5.2.14 on 2026-06-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritebook',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='thumbnail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
