# Generated by Django 5.2.14 on 2026-06-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_favoritebook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='meetup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
