# Generated by Django 6.0.5 on 2026-06-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_favoriteaudiobook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteaudiobook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
